FIG-30313: Create Radio component
figshare/fcl pull request #32
Opened 2023-05-18 10:41 UTC by ailincaibianca

[FIG-30313](https://digital-science.atlassian.net/browse/FIG-30313)

https://github.com/figshare/fcl/assets/63391401/b7644515-1929-4e0d-92d6-70bbad1d8870

2023-05-18 10:43 UTC, AlexBabusanu approved these changes

2023-05-18 12:13 UTC, antalutrazvan commented on packages/ui/input/radio/index.jsx
> +export default function Radio({ checked, className, disabled, error, label, onChange, value: inputValue }) {
@ailincaibianca destructure `{ ...other}` from the `props` object to the `<input` node. There are properties of importance to a `input type="radio"` to pass. Such as `name`.

Also, `id` sent to `<input` should not only be: `inputValue`.

Consider if the value is `1` for one `<Radio` but then another `<Radio` has the same value of `1` somewhere else in the app.

I would suggest we set it as either an explicitly passed `id` through props. or, if it is not passed, a combination of `name + value`:
```
 export default function Radio({ (...), id, name = "", ...others }) {
 const inputId = id ? id : `${name}-${inputValue}`;
 
```

2023-05-18 13:54 UTC, andreistangacianu commented on packages/ui/input/radio/index.css
> +  border: 1px solid #bbb;
this should be something from colors

2023-05-18 13:54 UTC, andreistangacianu commented on packages/ui/input/radio/index.css
> +  box-shadow: inset calc(2 * var(--gridSize)) calc(2 * var(--gridSize)) #bbb;
color plz

2023-05-18 13:55 UTC, andreistangacianu commented on packages/ui/input/radio/index.jsx
> +    if (onChange) {
let's test `typeof onChange === function` - it's sfer

2023-05-18 13:55 UTC, andreistangacianu commented on packages/ui/input/radio/index.jsx
> +    const { value } = event.target;
will `event.target` always exist ?

2023-05-18 14:00 UTC, andreistangacianu commented
Looks awesome, thank you!

2023-05-18 14:23 UTC, antalutrazvan requested changes

2023-05-18 16:06 UTC, ailincaibianca commented on packages/ui/input/radio/index.jsx
> +      onChange(value);
Fixed

2023-05-19 08:47 UTC, antalutrazvan approved these changes

2023-05-19 09:03 UTC, merged